# Generated by Django 4.2 on 2025-06-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_resource_remove_reservation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='type',
            field=models.CharField(choices=[('room', 'Chambre'), ('office', 'Bureau privé'), ('coworking', 'Espace de Travail'), ('meet', 'Salle de Reunion'), ('formation', 'Salle de Formation')], default='room', max_length=100),
        ),
    ]
