# Generated by Django 5.2.3 on 2025-06-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_alter_resource_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='category',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slot',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='slots/'),
        ),
        migrations.AddField(
            model_name='slot',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='slots/'),
        ),
        migrations.AddField(
            model_name='slot',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='slots/'),
        ),
        migrations.AddField(
            model_name='slot',
            name='map',
            field=models.CharField(default=3, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slot',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='slot',
            name='title',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
