# Generated by Django 5.2.3 on 2025-06-28 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_slot_category_slot_image1_slot_image2_slot_image3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='calendar_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
