# Generated by Django 5.2.3 on 2025-07-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_alter_slot_image1_alter_slot_image2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.CharField(blank=True, help_text='Ex: 🪑, 🌐, ☕, 🔐', max_length=10)),
            ],
        ),
    ]
