# Generated by Django 5.2.3 on 2025-07-06 14:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0008_slot_facilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
